### PR TITLE
Add weather script using DarkySky drop-in replacement PirateWeather.net

### PR DESCRIPTION
**Pull request by pca2**
Darksky's forecast API is in the process of shutting down and will [no longer be available after March 31, 2023](https://darksky.net/apple-weather). @alexander0042 has developed [pirateweather.net](https://pirateweather.net/) which functions as a drop-in replacement for the DarkSky API as well as the site [https://merrysky.net](https://merrysky.net) to visualize forecast data. This adds a fork of the Darksky based plugin developed by @seripap and @Scartiloffista that subs in the new API so that functionality can continue past DarkSky's demise.

### CODE REVIEW

**Comment by Scartiloffista** [comment]
with this planned deprecation, maybe directly replace it?

**Comment by pca2** [comment]
@Scartiloffista Sure, that's not a bad idea. In https://github.com/matryer/xbar-plugins/pull/1896/commits/ee2083e97f4a040280b5d26ef0bd31ff73151e8d I remove the DarkSky folder completely.

**Comment by sprak3000** [comment]
@pca2 

Looks like the branch has some conflicts. Could you resolve those?

**Comment by pca2** [comment]
@sprak3000 Thanks, should be up to date now and hopefully ready to merge

**Review by sprak3000 — APPROVED** [review]

**Pull request merged**
