### PR TITLE
Tracking Congress (First plugin using R)

### PR DESCRIPTION
**Pull request by jsowder**
(First Plugin to be built in R!)

Tracks US congressional bill action and individual members of the congress. 

Requires ProPublica Congress API Key.

### CODE REVIEW

**Comment by tresni** [comment]
Hey @jsowder , thanks for the PR.  It lead to me doing a bunch of research on R ;-) We require all plugins go through some kind of linting in order to help us know that they won't cause issues for people.  In my search I found [lintr](https://github.com/jimhester/lintr) and have put together a [basic test](https://github.com/matryer/bitbar-plugins/blob/b29860a6f6e1d3156aeb5969d4259f3b477e5d69/.test.py#L113-L125) as part of `.test.py`.

However, running it against your code comes back with a ton of issues (though most of them seem to be stylistic vs syntactical.) Is lintr a good place to start, do you have a better suggestion?  Below is the output of `./.test.py

```
$ ./.test.py Politics/congress.1h.R
WRN! /Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R missing recommended metadata for image

ERR! /Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R failed linting with "Rscript", please correct the following:

/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:28:3: style: Place a space before left parenthesis, except in a function call.
if(key_congress == "") stop("Register for an API Key | href=https://www.propublica.org/datastore/api/propublica-congress-api")
  ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:32:21: style: There should be a space between right parenthesis and an opening curly brace.
  function(pp_result){
                    ^~
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:51:1: style: Variable and function name style should be snake_case.
Recent <-
^~~~~~
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:76:7: style: Opening curly braces should never go on their own line and should always be followed by a new line.
      { if(dim(.)[1] == 0) tribble(~chamber, ~bill, ~info, "House", "No bills to show.", "") },
      ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:76:11: style: Place a space before left parenthesis, except in a function call.
      { if(dim(.)[1] == 0) tribble(~chamber, ~bill, ~info, "House", "No bills to show.", "") },
          ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:79:7: style: Opening curly braces should never go on their own line and should always be followed by a new line.
      { if(dim(.)[1] == 0) tribble(~chamber, ~bill, ~info, "Senate", "No bills to show.", "") },
      ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:79:11: style: Place a space before left parenthesis, except in a function call.
      { if(dim(.)[1] == 0) tribble(~chamber, ~bill, ~info, "Senate", "No bills to show.", "") },
          ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:82:1: style: Variable and function name style should be snake_case.
Upcoming <- tryCatch(
^~~~~~~~
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:83:3: style: Opening curly braces should never go on their own line and should always be followed by a new line.
  {
  ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:140:1: style: Variable and function name style should be snake_case.
Members <-
^~~~~~~
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:141:18: style: Trailing whitespace is superfluous.
  members_all %>%
                 ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:142:33: style: Trailing whitespace is superfluous.
  mutate(menu_title = "All") %>%
                                ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:143:61: style: Trailing whitespace is superfluous.
  bb_nest(menu_title, chamber, state, last_first, info) %T>%
                                                            ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:146:1: style: Variable and function name style should be snake_case.
Leadership <-
^~~~~~~~~~
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:147:18: style: Trailing whitespace is superfluous.
  members_all %>%
                 ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:148:33: style: Trailing whitespace is superfluous.
  filter(!is.na(leadership)) %>%
                                ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:149:31: style: Trailing whitespace is superfluous.
  arrange(desc(seniority)) %>%
                              ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:150:40: style: Trailing whitespace is superfluous.
  mutate(menu_title = "Leadership") %>%
                                       ^
/Users/bhartvig/Projects/bitbar-plugins/Politics/congress.1h.R:151:59: style: Trailing whitespace is superfluous.
  bb_nest(menu_title, chamber, leadership_role, info) %T>%


ERR! failed with 4 errors

$
```

**Comment by jsowder** [comment]
Hey @tresni, sorry for the delay! Glad you got to know R a little bit from this :-) It's a fun language!

As far as the linting goes, I've never used the `lintr` package before, but their docs say that their suggestions are included in the IDR that I use (RStudio). 

It does look like it's all stylistic, so I'm not sure why it's throwing 4 errors? I've certainly been using it in the meantime, without any issues!

**Comment by jsowder** [comment]
Just cleaned things up a bit, but the issues with Recent/Upcoming/Members/Leadership are throwing warnings because the lintr is interpreting objects as being functions. So those warnings will remain, but it looks like it's just an issue with `lintr`.

Hope this helps!

**Comment by jsowder** [comment]
Also sure why the lintr-bot is throwing that error, the pipe (%>%( from the magrittr package is very standard.

**Comment by sprak3000** [comment]
@jsowder 

Could you

1. Update the metadata tags from `<bitbar...` to `<xbar...`
2. Add a `<xbar.image>` metadata tag with a screenshot of your plugin in action

**Pull request merged**
