### PR TITLE
Add pidkiller plug-in to plugin repository

### PR DESCRIPTION
**Pull request by dengel29**
Made a plug-in which can display all running processes + process IDs (PIDs) and allows you to kill any upon clicking them.

### CODE REVIEW

**Comment by matryer** [comment]
@dengel29 amazing - Although I love the image, I wonder if you could make it a screenshot of what the plugin looks like when it's running?

**Comment by dengel29** [comment]
Thanks for the response! Yeah, can do mid next week, out for Chinese New Year for next few days. Cheers!

**Comment by matryer** [comment]
@dengel29 Happy New Year :D

**Comment by dengel29** [comment]
Hey @matryer here is a picture of the plug-in in action. Let me know if there's anything else I can do or any improvements you can think of. Thanks! 

PIDkiller in action

**Comment by matryer** [comment]
@dengel29 Can you update the image metadata to use this image too please?

**Comment by dengel29** [comment]
Sorry about the misunderstanding, I've updated the metadata with that image. Thanks for your patience!

**Comment by matryer** [comment]
@dengel29 thanks, great plugin.

**Pull request merged**
