### PR TITLE
Add new plugin:  jackpot

### PR DESCRIPTION
**Pull request by astrowonk**
I wasn't 100% the category but "Games" I guess is right? Finance certainly didn't seem correct. This displays the current Mega Millions and Powerball jackpots. It turns green if the jackpot size is over $200M. The menus link to the respective lottery web sites.

Feel free to re-categorize as you feel appropriate.

### CODE REVIEW

**Comment by astrowonk** [comment]
been over a year with this one, thought I'd check in...

**Comment by sprak3000** [comment]
@astrowonk 

Please add a `<xbar.image>` metadata tag linking to a screenshot of the plugin in action.

**Comment by astrowonk** [comment]
> @astrowonk
> 
> Please add a `<xbar.image>` metadata tag linking to a screenshot of the plugin in action.

Done. Also made a few minor tweaks (putting jackpot threshold in a constant) to bring to parity with my own repo.

**Review by sprak3000 — APPROVED** [review]

**Comment by astrowonk** [comment]
Thank you for merging! It doesn't appear in the xbar plugin in browser UI yet… if I misconfigured something and need to make another PR, let me know.

**Comment by sprak3000** [comment]
@astrowonk 

I believe that is a manual process. Will try to update here when it is updated.

**Pull request merged**
