### PR TITLE
Add zeit plugin

### PR DESCRIPTION
**Pull request by mrusme**
Add plugin for [`zeit`](https://github.com/mrusme/zeit),  a command line tool for tracking time spent on activities.

### CODE REVIEW

**Comment by mrusme** [comment]
The CI tells:

```
ERR! /Users/travis/build/matryer/xbar-plugins/Time/zeit.1m.sh missing required metadata for author
3054
3055ERR! /Users/travis/build/matryer/xbar-plugins/Time/zeit.1m.sh missing required metadata for author.github
3056
3057ERR! /Users/travis/build/matryer/xbar-plugins/Time/zeit.1m.sh missing required metadata for title
```

While the plugin actually contains the following definitions:

```sh
# <xbar.title>zeit</xbar.title>
# <xbar.author>Marius</xbar.author>
# <xbar.author.github>mrusme</xbar.author.github>
```

I don't see a difference to how [it's documented](https://github.com/matryer/xbar#metadata). 🤔

**Comment by matryer** [comment]
Ahh yes--this will be updated at some point.

**Comment by mrusme** [comment]
@matryer any updates here?

**Comment by mrusme** [comment]
:-(

**Comment by mrusme** [comment]
Whatever. 🙄

**Pull request closed without merging**
