### PR TITLE
Update Homebrew plugins to fix issue on Apple Silicon Macs and add Greedy option

### PR DESCRIPTION
**Pull request by jimeh**
This adds the latest [changes from my dotfiles](https://github.com/jimeh/dotfiles/compare/c7ea3d186a2e2c502c05fbe73d12685006aa8848...14c58e849f7c986eb8ed336a5e786e1c17ca16cc).

### CODE REVIEW

**Comment by onaforeignshore** [comment]
I used the updated code and it doesn't run in xbar, but it does in the terminal?

```
VAR_GROUPS="true" VAR_BREW_PATH="" VAR_HIDDEN_SERVICES="" '/Users/chris/Library/Application Support/xbar/plugins/brew-services.10m.rb'                                                                                26-02-23   22:48:07 
:bulb:0 | dropdown="false"
---
Brew Services
1 stopped
-----
--:hourglass: Refresh | refresh="true"
-----
--Start All (1 services) | terminal="false" refresh="true" shell="/opt/homebrew/bin/brew" param1="services" param2="start" param3="--all"
--Stop All (0 services)
--Restart All (1 services) | terminal="false" refresh="true" shell="/opt/homebrew/bin/brew" param1="services" param2="restart" param3="--all"
-----
--Disable groups | refresh="true" shell="/Users/chris/Library/Application Support/xbar/plugins/brew-services.10m.rb" param1="disable_groups"
---
Stopped (1):
:ballot_box_with_check: unbound
--Start | terminal="false" refresh="true" shell="/opt/homebrew/bin/brew" param1="services" param2="start" param3="unbound"
-----
--Status: none
--User: <none>
-----
--Hide | refresh="true" shell="/Users/chris/Library/Application Support/xbar/plugins/brew-services.10m.rb" param1="hide" param2="unbound"
--Uninstall
----Are you sure?
-------
----Yes | terminal="true" refresh="false" shell="/opt/homebrew/bin/brew" param1="uninstall" param2="unbound" param3=";" param4="open" param5="-jg" param6="'xbar://app.xbarapp.com/refreshPlugin?path=brew-services.10m.rb'"
```

Also, I don't have services installed, and `brew services list` returns

```
Name    Status User File
unbound none
```

Something else that needs to be addressed?

**Comment by jimeh** [comment]
@onaforeignshore Are you sure you don't have the `unbound` formula installed?

What do these commands return?

```command
brew services list --json
```
```command
brew list --versions | grep unbound
```

**Review by sprak3000 — APPROVED** [review]
@jimeh 

Love the pattern here for determining where Homebrew lives.

**Comment by onaforeignshore** [comment]
I double checked and apparently it is installed. My bad, sorry.

From: Jim Myhrberg ***@***.***>
Date: Monday, 27 February 2023 at 00:31
To: matryer/xbar-plugins ***@***.***>
Cc: Christo Kotze ***@***.***>, Mention ***@***.***>
Subject: Re: [matryer/xbar-plugins] Update Homebrew plugins to fix issue on Apple Silicon Macs and add Greedy option (PR #1921)

@onaforeignshore<https://github.com/onaforeignshore> Are you sure you don't have the unbound formula installed?

What do these commands return?

brew services list --json

brew list --versions | grep unbound

**Pull request merged**
