### PR TITLE
New plugin to manipulate clipboard text

### PR DESCRIPTION
**Pull request by gomedia-adi**

### CODE REVIEW

**Comment by matryer** [comment]
@gomedia-adi this is amazing - can you fix the conflicts and I'll merge this?

**Comment by gomedia-adi** [comment]
Do you mean "The command "brew outdated python@2 || brew upgrade python@2" failed and exited with 1 during ."?

Nothing to do with me - I'm just chucking the code into the mix!

**Review by gomedia-adi — COMMENTED** [review]
Try to commit again ...

**Comment by matryer** [comment]
@gomedia-adi I really want to merge this, but something strange is going on: https://github.com/matryer/xbar-plugins/pull/1500/conflicts

Can we do one PR for each of these? Sorry if that's a pain.

**Review by sprak3000 — APPROVED** [review]

**Pull request merged**
