### PR TITLE
feat(Dev/Homebrew/brew-updates): new options and style changes

### PR DESCRIPTION
**Pull request by jimeh**
- Add more granular greedy options (latest and auto-updates).
- Add post-run options for optionally running "brew cleanup" and/or
  "brew doctor" after operations that modify packages.
- Add new "Upgrade All: Exclude" option which simply excludes a
  formula/cask when using any of the Upgrade All operations.
- Re-style menus a bit with emoji as icons for most operations.

---

This pulls in the latest changes to the brew-updates plugin from my [dotfiles](https://github.com/jimeh/dotfiles/tree/main/xbar).

**Before:**

before

**After:**

after

settings

### CODE REVIEW

**Comment by onaforeignshore** [comment]
Tried to run this and got:

```
ERROR: undefined method `split' for true:TrueClass:
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:490:in `greedy_types'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:494:in `greedy_latest?'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:503:in `greedy_args'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:509:in `outdated_args'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:513:in `outdated'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:482:in `all_formulas'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:474:in `formulas'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:267:in `run'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:40:in `run'
	/Users/chris/Library/Application Support/xbar/plugins/brew-updates.1h.rb:520:in `<main>'
```

**Comment by onaforeignshore** [comment]
Also, a suggestion - can you add two more options?
[ ] Run Brew Cleanup
[ ] Run Brew Doctor

I like to do a cleanup after install to clean out old versions and then doctor to make sure that homebrew is healthy.

**Comment by onaforeignshore** [comment]
I got it working by deleting the `*.vars.json` file and then manually entering `/opt/homebrew/bin/brew`

**Comment by jimeh** [comment]
That split error is cause the greedy value was a boolean in the JSON config. I forgot that values aren't normalized to strings via env vars, as I directly read the JSON config file 🤦‍♂️. Easy enough to handle correctly though :)

And I believe the failure to auto-detect brew is cause the config option had a default value previously, which got written to your config file. Auto-detection kicks in when no value has been set. I should be able to fix this by falling back to auto-detection if the specified value does not exist on disk.

Thanks yet again for your testing/QA efforts @onaforeignshore :)

**Comment by jimeh** [comment]
@onaforeignshore Your issues should now be fixed. And I'll have a look at adding the extra options you wanted shortly :)

**Comment by jimeh** [comment]
@onaforeignshore Tooks me longer than I thought to have time to tidy this up. But I've had the post-run features working locally for a few days now. Hopefully this should all work for you :)

**Comment by onaforeignshore** [comment]
Hi @jimeh 

Got this interesting one today...
```
❯ VAR_GREEDY_LATEST="true" VAR_GREEDY_AUTO_UPDATES="true" VAR_POST_RUN_CLEANUP="true" VAR_POST_RUN_DOCTOR="true" VAR_BREW_PATH="" VAR_GREEDY="auto_updates,latest" '/opt/homebrew/bin/brew' upgrade ghostscript dash skype && /opt/homebrew/bin/brew cleanup ghostscript dash skype && /opt/homebrew/bin/brew doctor ; open -jg 'xbar://app.xbarapp.com/refreshPlugin?path=brew-updates.1h.rb'
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: Treating dash as a formula. For the cask, use homebrew/cask/dash
Error: dash not installed
==> Upgrading 1 outdated package:
ghostscript 10.01.0 -> 10.01.1
==> Fetching ghostscript
==> Downloading https://ghcr.io/v2/homebrew/core/ghostscript/manifests/10.01.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:2d9684b51e348763e405edf791bf70c097403488776c2a1a079373eeb077edb5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:2d9684b51e348763e405edf791bf70c097403488776c2a1a079373eeb077edb5?se=2023-03-28T08%3A20%3A00Z&sig=Eb5hkb0NNTHzy2TTIUsmV0f3aobF9nRn%2FH2j7DEH7yM
######################################################################## 100.0%
==> Upgrading ghostscript
  10.01.0 -> 10.01.1 

==> Pouring ghostscript--10.01.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/ghostscript/10.01.1: 645 files, 151.5MB
==> Running `brew cleanup ghostscript`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/ghostscript/10.01.0... (645 files, 151.5MB)
==> Upgrading 1 outdated package:
skype 8.95.0.408 -> 8.96.0.207
==> Upgrading skype
==> Downloading https://endpoint920510.azureedge.net/s4l/s4l/download/mac/Skype-8.96.0.207.dmg
######################################################################## 100.0%
==> Backing App 'Skype.app' up to '/opt/homebrew/Caskroom/skype/8.95.0.408/Skype.app'
==> Removing App '/Applications/Skype.app'
==> Moving App 'Skype.app' to '/Applications/Skype.app'
==> Purging files for version 8.95.0.408 of Cask skype
🍺  skype was successfully upgraded!
user=8.62s system=6.21s cpu=29% total=50.614
```

Notice what it says about `dash`. All other casks so far updated normally.

I know when I update a cask I usually do `brew update --cask ...`

**Comment by jimeh** [comment]
@onaforeignshore the `dash` upgrade should now work. From the Upgrade All option I decided to run `brew upgrade` twice, for formulas and casks separately, to try an avoid making the command stupidly long by duplicating `homebrew/cask/` for each cask.

**Review by sprak3000 — APPROVED** [review]

**Comment by onaforeignshore** [comment]
This works fine on my M1, but on my Mac Mini (Catalina - 10.15.7) with `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

Screen Shot 2023-04-06 at 13 29 03

Any ideas?

**Pull request merged**
