### PR TITLE
Create rebootreminder.1h.sh

### PR DESCRIPTION
**Pull request by lawtalker**

### CODE REVIEW

**Review by sprak3000 — APPROVED** [review]
Will chmod in a separate PR.

**Comment by lawtalker** [comment]
do you know how often the list in the plugin browser in the app (or on the xbar webpage) is updated? (my plugin is not yet showing)

**Comment by sprak3000** [comment]
@lawtalker 

It's a process @matryer needs to kick off. @matryer Any chance we can get a refresh of the browser data? Been awhile...

**Comment by lawtalker** [comment]
it looks like this is now updating automatically ever week? woohoo!

**Pull request merged**
